### PR TITLE
add three more errors

### PR DESCRIPTION
**Pull request by Blackcipher101**

### CODE REVIEW

**Comment by VSevagen** [comment]
The missing 'tasks' in settings.py is ok but the other 2 errors would lead to a different workflow. First they'll have to fix the api and so they are redirected to it in the beginning, then they'll have to find a way to get back to the homepage. This workflow is what we're going for so the other 2 errors, change them.

**Comment by Blackcipher101** [comment]
Ok, I will look into some other errors

**Comment by Blackcipher101** [comment]
Added two errors one with url request and one with passing of variables to template

**Comment by VSevagen** [comment]
Change this pr to have only the "not listed in installed app" error. I saw the new error but it still causes a change in the workflow. We'll just have this "not in installed apps" as an addition but remove the rest alright :)

**Comment by Blackcipher101** [comment]
Ok :)

**Comment by VSevagen** [comment]
Your branch was a bit messy + you had 4 commits instead of 1. I was kind of tired just commenting so I just did the commit. I added you as co-author so no worries bout that. I will close this one now.

**Pull request closed without merging**
